name: chatbox
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.4.1
  flutter_svg: ^2.0.10+1
  social_auth_buttons: ^2.0.2
  pinput: ^5.0.0
  flutter_sliding_box: ^1.1.5
  flutter_bloc: ^8.1.6
  firebase_auth: any
  qr_flutter: ^4.1.0
  cloud_firestore: ^5.4.1
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Caros
      fonts:
        - asset: assets/fonts/cretype  Caros.otf


flutter_assets:
  assets_path: assets/svgs/
  output_path: lib/utils/
  filename: svgs.dart
  field_prefix: